BASE_PATH = "/Users/xuel12/Documents/MSdatascience/DS5500datavis/project2/"
CODE_DIR = BASE_PATH + "h1permprediction/"
INPUT_DIR = BASE_PATH + "input_h1b/"
INPUT_DIR_PERM = BASE_PATH + "input_perm/"
TEMP_DIR = BASE_PATH + "temp/"
OUTPUT_DIR = BASE_PATH + "output/"
PREDICT_DIR = BASE_PATH + "predict/"
DOWNLOAD_DIR = BASE_PATH + "download/"
HEADER_DIR = CODE_DIR + "header/"
MODEL_DIR = CODE_DIR + "model/"


HEADERS = [
                'CASE_NUMBER',
                'CASE_STATUS',
                'CASE_SUBMITTED',
                'DECISION_DATE',
                'VISA_CLASS',
                'JOB_TITLE',
                'SOC_CODE',
                'SOC_TITLE',
                'FULL_TIME_POSITION',
                'PERIOD_OF_EMPLOYMENT_START_DATE',
                'PERIOD_OF_EMPLOYMENT_END_DATE',
                'TOTAL_WORKER_POSITIONS',
                'NEW_EMPLOYMENT',
                'CONTINUED_EMPLOYMENT',
                'CHANGE_PREVIOUS_EMPLOYMENT',
                'NEW_CONCURRENT_EMPLOYMENT',
                'CHANGE_EMPLOYER',
                'AMENDED_PETITION',
                'EMPLOYER_NAME',
                'EMPLOYER_BUSINESS_DBA',
                # 'EMPLOYER_ADDRESS1',
                # 'EMPLOYER_ADDRESS2',
                'EMPLOYER_CITY',
                'EMPLOYER_STATE',
                'EMPLOYER_POSTAL_CODE',
                'EMPLOYER_COUNTRY',
                'EMPLOYER_PROVINCE',
                # 'EMPLOYER_PHONE',
                # 'EMPLOYER_PHONE_EXT',
                'NAICS_CODE',
                'AGENT_REPRESENTING_EMPLOYER',
                'AGENT_ATTORNEY_LAW_FIRM_BUSINESS_NAME',
                # 'AGENT_ATTORNEY_ADDRESS1',
                # 'AGENT_ATTORNEY_ADDRESS2',
                'AGENT_ATTORNEY_CITY',
                'AGENT_ATTORNEY_STATE',
                'AGENT_ATTORNEY_POSTAL_CODE',
                'AGENT_ATTORNEY_COUNTRY',
                'AGENT_ATTORNEY_PROVINCE',
                # 'STATE_OF_HIGHEST_COURT',
                'NAME_OF_HIGHEST_STATE_COURT'
            ]

PARSE_DATES = ['CASE_SUBMITTED', 'DECISION_DATE', 
               'PERIOD_OF_EMPLOYMENT_START_DATE', 'PERIOD_OF_EMPLOYMENT_END_DATE']

COL_TYPES = {
            'CASE_NUMBER': 'str',
            'CASE_STATUS': 'str',
            'CASE_SUBMITTED': 'str',
            'DECISION_DATE': 'str',
            'ORIGINAL_CERT_DATE': 'str',
            'VISA_CLASS': 'str',
            'JOB_TITLE': 'str',
            'SOC_CODE': 'str',
            'SOC_TITLE': 'str',
            'FULL_TIME_POSITION': 'str',
            'PERIOD_OF_EMPLOYMENT_START_DATE': 'str',
            'PERIOD_OF_EMPLOYMENT_END_DATE': 'str',
            'TOTAL_WORKER_POSITIONS': 'str',
            'NEW_EMPLOYMENT': 'str',
            'CONTINUED_EMPLOYMENT': 'str',
            'CHANGE_PREVIOUS_EMPLOYMENT': 'str',
            'NEW_CONCURRENT_EMPLOYMENT': 'str',
            'CHANGE_EMPLOYER': 'str',
            'AMENDED_PETITION': 'str',
            'EMPLOYER_NAME': 'str',
            'EMPLOYER_BUSINESS_DBA': 'str',
            'EMPLOYER_ADDRESS1': 'str',
            'EMPLOYER_ADDRESS2': 'str',
            'EMPLOYER_CITY': 'str',
            'EMPLOYER_STATE': 'str',
            'EMPLOYER_POSTAL_CODE': 'str',
            'EMPLOYER_COUNTRY': 'str',
            'EMPLOYER_PROVINCE': 'str',
            'EMPLOYER_PHONE': 'str',
            'EMPLOYER_PHONE_EXT': 'str',
            'NAICS_CODE': 'str',
            'AGENT_REPRESENTING_EMPLOYER': 'str',
            'AGENT_ATTORNEY_LAW_FIRM_BUSINESS_NAME': 'str',
            'AGENT_ATTORNEY_ADDRESS1': 'str',
            'AGENT_ATTORNEY_ADDRESS2': 'str',
            'AGENT_ATTORNEY_CITY': 'str',
            'AGENT_ATTORNEY_STATE': 'str',
            'AGENT_ATTORNEY_POSTAL_CODE': 'str',
            'AGENT_ATTORNEY_COUNTRY': 'str',
            'AGENT_ATTORNEY_PROVINCE': 'str',
            'AGENT_ATTORNEY_PHONE': 'str',
            'AGENT_ATTORNEY_PHONE_EXT': 'str',
            'STATE_OF_HIGHEST_COURT': 'str',
            'NAME_OF_HIGHEST_STATE_COURT': 'str'}

SOC_MAP = {
        '11': 'MANAGERIAL, ADMIN',
        '13': 'FINANCIALS, COMPLIANCE',
        '15': 'COMPUTING, STATISTICIANS',
        '17': 'ENGINEERING EXCEPT COMPUTERS' ,
        '19': 'SCIENTISTS' ,
        '21': 'PSYCHOLOGY , COUNSELLING , SOCIAL WORKS' ,
        '23': 'LEGAL' ,
        '25': 'EDUCATORS , CURATORS' ,
        '27': 'DESIGNERS , COACHES' ,
        '29': 'MEDICALS' ,
        '31': 'HEALTHCARE ASSTS' ,
        '33': 'SECURITY' ,
        '35': 'CULINARY' ,
        '37': 'CLEANING , KEEPING' ,
        '39': 'RECEIPTIONISTS , SERVICE ATTENDANTS' ,
        '40': 'ENGINEERING EXCEPT COMPUTERS' ,
        '41': 'TRADERS , SALES REPS' ,
        '43': 'QUALITY , STATISTICAL ASSTS' ,
        '45': 'AGRICULTURAL' ,
        '47': 'ARTISANS' ,
        '49': 'SERVICE TECHNICIANS' ,
        '51': 'MACHINISTS' ,
        '53': 'TRANSPORT' ,
        '71': 'ENGINEERING EXCEPT COMPUTERS' }

PW_WAGE_LEVEL_MAP = {
        '1': 'LEVEL I',
        '2': 'LEVEL II',
        '3': 'LEVEL III',
        '4': 'LEVEL IV',
        'I': 'LEVEL I',
        'II': 'LEVEL II',
        'III': 'LEVEL III',
        'IV': 'LEVEL IV'}

US_STATE_ABBREV = {
    'ALABAMA': 'AL',
    'ALASKA': 'AK',
    'AMERICAN SAMOA': 'AS',
    'ARIZONA': 'AZ',
    'ARKANSAS': 'AR',
    'CALIFORNIA': 'CA',
    'COLORADO': 'CO',
    'CONNECTICUT': 'CT',
    'DELAWARE': 'DE',
    'DISTRICT OF COLUMBIA': 'DC',
    'FLORIDA': 'FL',
    'GEORGIA': 'GA',
    'GUAM': 'GU',
    'HAWAII': 'HI',
    'IDAHO': 'ID',
    'ILLINOIS': 'IL',
    'INDIANA': 'IN',
    'IOWA': 'IA',
    'KANSAS': 'KS',
    'KENTUCKY': 'KY',
    'LOUISIANA': 'LA',
    'MAINE': 'ME',
    'MARYLAND': 'MD',
    'MASSACHUSETTS': 'MA',
    'MICHIGAN': 'MI',
    'MINNESOTA': 'MN',
    'MISSISSIPPI': 'MS',
    'MISSOURI': 'MO',
    'MONTANA': 'MT',
    'NEBRASKA': 'NE',
    'NEVADA': 'NV',
    'NEW HAMPSHIRE': 'NH',
    'NEW JERSEY': 'NJ',
    'NEW MEXICO': 'NM',
    'NEW YORK': 'NY',
    'NORTH CAROLINA': 'NC',
    'NORTH DAKOTA': 'ND',
    'NORTHERN MARIANA ISLANDS':'MP',
    'OHIO': 'OH',
    'OKLAHOMA': 'OK',
    'OREGON': 'OR',
    'PENNSYLVANIA': 'PA',
    'PUERTO RICO': 'PR',
    'RHODE ISLAND': 'RI',
    'SOUTH CAROLINA': 'SC',
    'SOUTH DAKOTA': 'SD',
    'TENNESSEE': 'TN',
    'TEXAS': 'TX',
    'UTAH': 'UT',
    'VERMONT': 'VT',
    'VIRGIN ISLANDS': 'VI',
    'VIRGINIA': 'VA',
    'WASHINGTON': 'WA',
    'WEST VIRGINIA': 'WV',
    'WISCONSIN': 'WI',
    'WYOMING': 'WY',
    'AL': 'AL',
    'AK': 'AK',
    'AS': 'AS',
    'AZ': 'AZ',
    'AR': 'AR',
    'CA': 'CA',
    'CO': 'CO',
    'CT': 'CT',
    'DE': 'DE',
    'DC': 'DC',
    'FL': 'FL',
    'GA': 'GA',
    'GU': 'GU',
    'HI': 'HI',
    'ID': 'ID',
    'IL': 'IL',
    'IN': 'IN',
    'IA': 'IA',
    'KS': 'KS',
    'KY': 'KY',
    'LA': 'LA',
    'ME': 'ME',
    'MD': 'MD',
    'MA': 'MA',
    'MI': 'MI',
    'MN': 'MN',
    'MS': 'MS',
    'MO': 'MO',
    'MT': 'MT',
    'NE': 'NE',
    'NV': 'NV',
    'NH': 'NH',
    'NJ': 'NJ',
    'NM': 'NM',
    'NY': 'NY',
    'NC': 'NC',
    'ND': 'ND',
    'MP':'MP',
    'OH': 'OH',
    'OK': 'OK',
    'OR': 'OR',
    'PA': 'PA',
    'PR': 'PR',
    'RI': 'RI',
    'SC': 'SC',
    'SD': 'SD',
    'TN': 'TN',
    'TX': 'TX',
    'UT': 'UT',
    'VT': 'VT',
    'VI': 'VI',
    'VA': 'VA',
    'WA': 'WA',
    'WV': 'WV',
    'WI': 'WI',
    'WY': 'WY',
    'UNKNOWN': 'UNKNOWN'
 }


JOB_LEVEL_MAP = {
    'UNKNOWN':'UNKNOWN',
    'Level I': 'LEVEL I',
    'Level II': 'LEVEL II',
    'Level III': 'LEVEL III',
    'Level IV': 'LEVEL IV',
    'LEVEL I': 'LEVEL I',
    'LEVEL II': 'LEVEL II',
    'LEVEL III': 'LEVEL III',
    'LEVEL IV': 'LEVEL IV',

}

UNIT_MAP = {
    'Year':'YEAR',
    'Bi-Weekly':'BI-WEEKLY',
    'Hour':'HOUR',
    'Month':'MONTH',
    'Week':'WEEK',
    'NAN': 'UNKNOWN',
}

H1B_TRAIN_FEATURES = [
    'CASE_STATUS',
    'EMPLOYER_STATE',
    'WORKSITE_STATE',
    'JOB_CATEGORY',
    'JOB_LEVEL',
    'FULL_TIME_POSITION',
    'PW_UNIT_OF_PAY',
    'PW_WAGE_LEVEL',
    'H-1B_DEPENDENT',
    'WILLFUL_VIOLATOR'
]

H1B_CATEG_FEATURES = [
    'EMPLOYER_STATE',
    'WORKSITE_STATE',
    'JOB_CATEGORY',
    'JOB_LEVEL',
    'FULL_TIME_POSITION',
    'PW_UNIT_OF_PAY',
    'PW_WAGE_LEVEL', 
    'H-1B_DEPENDENT',
    'WILLFUL_VIOLATOR'
]

PERM_TRAIN_FEATURES = [
    "CASE_STATUS", "REFILE",
    "FW_OWNERSHIP_INTEREST","PW_LEVEL_9089",
    "JOB_INFO_WORK_STATE" , "JOB_INFO_EDUCATION" , "JOB_INFO_TRAINING",
    "JOB_INFO_ALT_FIELD" ,"JOB_INFO_JOB_REQ_NORMAL" ,"JOB_INFO_FOREIGN_LANG_REQ",
    "JOB_INFO_COMBO_OCCUPATION",
    "RECR_INFO_COLL_UNIV_TEACHER",
    "FW_INFO_BIRTH_COUNTRY", "CLASS_OF_ADMISSION",
    "FW_INFO_TRAINING_COMP" 
]

PERM_CATEG_FEATURES = [
    "REFILE",
    "FW_OWNERSHIP_INTEREST","PW_LEVEL_9089",
    "JOB_INFO_WORK_STATE" , "JOB_INFO_EDUCATION" , "JOB_INFO_TRAINING",
    "JOB_INFO_ALT_FIELD" ,"JOB_INFO_JOB_REQ_NORMAL" ,"JOB_INFO_FOREIGN_LANG_REQ",
    "JOB_INFO_COMBO_OCCUPATION",
    "RECR_INFO_COLL_UNIV_TEACHER",
    "FW_INFO_BIRTH_COUNTRY", "CLASS_OF_ADMISSION",
    "FW_INFO_TRAINING_COMP"
]

STATE_DROPDOWN = [
    'AL',
    'AK',
    'AS',
    'AZ',
    'AR',
    'CA',
    'CO',
    'CT',
    'DE',
    'DC',
    'FL',
    'GA',
    'GU',
    'HI',
    'ID',
    'IL',
    'IN',
    'IA',
    'KS',
    'KY',
    'LA',
    'ME',
    'MD',
    'MA',
    'MI',
    'MN',
    'MS',
    'MO',
    'MT',
    'NE',
    'NV',
    'NH',
    'NJ',
    'NM',
    'NY',
    'NC',
    'ND',
    'MP',
    'OH',
    'OK',
    'OR',
    'PA',
    'PR',
    'RI',
    'SC',
    'SD',
    'TN',
    'TX',
    'UT',
    'VT',
    'VI',
    'VA',
    'WA',
    'WV',
    'WI',
    'WY',
    'UNKNOWN'
]


JOB_CATEGORY_DROPDOWN = [
    'MANAGERIAL, ADMIN',
    'FINANCIALS, COMPLIANCE',
    'COMPUTING, STATISTICIANS',
    'ENGINEERING EXCEPT COMPUTERS',
    'SCIENTISTS',
    'PSYCHOLOGY , COUNSELLING , SOCIAL WORKS',
    'LEGAL',
    'EDUCATORS , CURATORS',
    'DESIGNERS , COACHES',
    'MEDICALS',
    'HEALTHCARE ASSTS',
    'SECURITY',
    'CULINARY',
    'CLEANING , KEEPING',
    'RECEIPTIONISTS , SERVICE ATTENDANTS',
    'ENGINEERING EXCEPT COMPUTERS',
    'TRADERS , SALES REPS',
    'QUALITY , STATISTICAL ASSTS',
    'AGRICULTURAL',
    'ARTISANS',
    'SERVICE TECHNICIANS',
    'MACHINISTS',
    'TRANSPORT',
    'UNKNOWN',
    'ENGINEERING EXCEPT COMPUTERS',
    'OTHER'
]


JOB_LEVEL_DROPDOWN = [
    'SENIOR',
    'JUNIOR',
    'UNKNOWN',
    'OTHER'
]


FULL_TIME_POSITION_DROPDOWN = [
    'Y',
    'UNKNOWN',
    'N',
]

PW_UNIT_OF_PAY_DROPDOWN = [
    'YEAR',
    'BI-WEEKLY',
    'HOUR',
    'MONTH',
    'UNKNOWN',
    'WEEK',
]

PW_WAGE_LEVEL_DROPDOWN = [
    'UNKNOWN',
    'LEVEL I',
    'LEVEL II',
    'LEVEL III',
    'LEVEL IV',
]

H1B_DEPENDENT_DROPDOWN = [
    'Y',
    'N',
    'UNKNOWN',
]

WILLFUL_VIOLATOR_DROPDOWN = [
    'Y',
    'N',
]

PERM_REFILE_DROPDOWN = [
    'N',
    'UNKNOWN',
    'Y'
]

PERM_FW_OWNERSHIP_INTEREST_DROPDOWN = [
    'N',
    'UNKNOWN',
    'Y'
]

PERM_PW_LEVEL_9089_DROPDOWN = [
    "LEVEL I",
    "LEVEL II",
    "LEVEL III",
    "LEVEL IV",
    'UNKNOWN',
]

PERM_JOB_INFO_EDUCATION_DROPDOWN = [
    "ASSOCIATE'S",
    "BACHELOR'S",
    'DOCTORATE',
    'HIGH SCHOOL',
    "MASTER'S",
    'UNKNOWN',
    'NONE',
    'OTHER'
]


PERM_JOB_INFO_TRAINING_DROPDOWN = [
    'N',
    'UNKNOWN',
    'Y'
]

PERM_JOB_INFO_ALT_FIELD_DROPDOWN = [
    'N',
    'UNKNOWN',
    'Y'
]

PERM_JOB_INFO_JOB_REQ_NORMAL_DROPDOWN = [
    'N',
    'UNKNOWN',
    'Y'
]

PERM_JOB_INFO_FOREIGN_LANG_REQ_DROPDOWN = [
    'N',
    'UNKNOWN',
    'Y'
]

PERM_RECR_INFO_PROFESSIONAL_OCC_DROPDOWN = [
    'N',
    'UNKNOWN',
    'Y'
]

PERM_RECR_INFO_COLL_UNIV_TEACHER_DROPDOWN = [
    'N',
    'UNKNOWN',
    'Y'
]

PERM_FW_INFO_BIRTH_COUNTRY_DROPDOWN = [
    "AFGHANISTAN",
    "ALBANIA",
    "ALGERIA",
    "ANGOLA",
    "ANTIGUA AND BARBUDA",
    "ARGENTINA",
    "ARMENIA",
    "ARUBA",
    "AUSTRALIA",
    "AUSTRIA",
    "AZERBAIJAN",
    "BAHAMAS",
    "BAHRAIN",
    "BANGLADESH",
    "BARBADOS",
    "BELARUS",
    "BELGIUM",
    "BELIZE",
    "BENIN",
    "BERMUDA",
    "BHUTAN",
    "BOLIVIA",
    "BOSNIA AND HERZEGOVINA",
    "BOTSWANA",
    "BRAZIL",
    "BRUNEI",
    "BULGARIA",
    "BURKINA FASO",
    "BURMA (MYANMAR)",
    "CAMBODIA",
    "CAMEROON",
    "CANADA",
    "CHAD",
    "CHILE",
    "CHINA",
    "COLOMBIA",
    "COSTA RICA",
    "COTE d'IVOIRE",
    "CROATIA",
    "CUBA",
    "CURACAO",
    "CYPRUS",
    "CZECH REPUBLIC",
    "CZECHOSLOVAKIA",
    "DEMOCRATIC REPUBLIC OF CONGO",
    "DENMARK",
    "DOMINICAN REPUBLIC",
    "ECUADOR",
    "EGYPT",
    "EL SALVADOR",
    "ERITREA",
    "ESTONIA",
    "ETHIOPIA",
    "FIJI",
    "FINLAND",
    "FRANCE",
    "GABON",
    "GAMBIA",
    "GEORGIA",
    "GERMANY",
    "GHANA",
    "GREECE",
    "GRENADA",
    "GUATEMALA",
    "GUYANA",
    "HAITI",
    "HONDURAS",
    "HONG KONG",
    "HUNGARY",
    "ICELAND",
    "INDIA",
    "INDONESIA",
    "IRAN",
    "IRAQ",
    "IRELAND",
    "ISRAEL",
    "ITALY",
    "JAMAICA",
    "JAPAN",
    "JORDAN",
    "KAZAKHSTAN",
    "KENYA",
    "KOSOVO",
    "KUWAIT",
    "KYRGYZSTAN",
    "LAOS",
    "LATVIA",
    "LEBANON",
    "LESOTHO",
    "LIBERIA",
    "LIBYA",
    "LITHUANIA",
    "LUXEMBOURG",
    "MACAU",
    "MACEDONIA",
    "MALAWI",
    "MALAYSIA",
    "MALI",
    "MAURITANIA",
    "MAURITIUS",
    "MEXICO",
    "MOLDOVA",
    "MONGOLIA",
    "MONTENEGRO",
    "MOROCCO",
    "MOZAMBIQUE",
    "NAMIBIA",
    "NEPAL",
    "NETHERLANDS",
    "NETHERLANDS ANTILLES",
    "NEW ZEALAND",
    "NICARAGUA",
    "NIGER",
    "NIGERIA",
    "NORWAY",
    "OMAN",
    "PAKISTAN",
    "PALAU",
    "PALESTINE",
    "PALESTINIAN TERRITORIES",
    "PANAMA",
    "PAPUA NEW GUINEA",
    "PARAGUAY",
    "PERU",
    "PHILIPPINES",
    "POLAND",
    "PORTUGAL",
    "QATAR",
    "REPUBLIC OF CONGO",
    "ROMANIA",
    "RUSSIA",
    "RWANDA",
    "SAUDI ARABIA",
    "SENEGAL",
    "SERBIA",
    "SERBIA AND MONTENEGRO",
    "SIERRA LEONE",
    "SINGAPORE",
    "SINT MAARTEN",
    "SLOVAKIA",
    "SLOVENIA",
    "SOUTH AFRICA",
    "SOUTH KOREA",
    "SOVIET UNION",
    "SPAIN",
    "SRI LANKA",
    "ST LUCIA",
    "ST VINCENT",
    "SUDAN",
    "SWAZILAND",
    "SWEDEN",
    "SWITZERLAND",
    "SYRIA",
    "TAIWAN",
    "TAJIKISTAN",
    "TANZANIA",
    "THAILAND",
    "TOGO",
    "TRINIDAD AND TOBAGO",
    "TUNISIA",
    "TURKEY",
    "TURKMENISTAN",
    "UGANDA",
    "UKRAINE",
    "UNITED ARAB EMIRATES",
    "UNITED KINGDOM",
    "UNITED STATES OF AMERICA",
    'UNKNOWN',
    "URUGUAY",
    "UZBEKISTAN",
    "VENEZUELA",
    "VIETNAM",
    "YEMEN",
    "YUGOSLAVIA",
    "ZAMBIA",
    "ZIMBABWE",

]

PERM_CLASS_OF_ADMISSION_DROPDOWN = [
    'A-3',
    'A1/A2',
    'B-1',
    'B-2',
    'C-1',
    'C-3',
    'D-1',
    'E-1',
    'E-2',
    'E-3',
    'EWI',
    'F-1',
    'F-2',
    'G-1',
    'G-4',
    'G-5',
    'H-1A',
    'H-1B',
    'H-1B1',
    'H-2A',
    'H-2B',
    'H-3',
    'H-4',
    'I',
    'J-1',
    'J-2',
    'K-1',
    'K-4',
    'L-1',
    'L-2',
    'M-1',
    'M-2',
    'N',
    'NOT IN USA',
    'O-1',
    'O-2',
    'O-3',
    'P-1',
    'P-2',
    'P-3',
    'P-4',
    'PAROLEE',
    'Q',
    'R-1',
    'R-2',
    'S-6',
    'T-1',
    'T-2',
    'TD',
    'TN',
    'TPS',
    'U-1',
    'UNKNOWN',
    'V-1',
    'V-2',
    'VWB',
    'VWT'
]

PERM_FW_INFO_TRAINING_COMP_DROPDOWN = [
    'A',
    'N',
    'Y',
    'UNKNOWN'
]